swagger: '2.0'
info:
  description: API for ToDo List
  version: 1.0
  title: ToDo List API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: 127.0.0.1
basePath: /
schemes:
  - https
  - http
paths:
  /list/{list_id}:
    get:
      summary: All Entries
      description: All Entries from a specific ToDo List
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: list_id
          in: path
          description: ID of list
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/TodoList'
        '404':
          description: invalid list id
    delete:
      summary: ...
      description: Delete a ToDo List with all Entries
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: list_id
          in: path
          description: ID of list
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: sucessful operation
          schema:
            $ref: '#/definitions/TodoList'
        '404':
          description: invalid list id


definitions:
  TodoList:
    type: object
    properties:
      id:
        type: integer
        format: int32
      name:
        type: string
      entries:
        type: array
        items:
          $ref: '#/definitions/TodoEntry'
  TodoEntry:
    type: object
